name: lint and build checks

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/check.yml'
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/check.yml'
      - 'src/**'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: yarn install
        run: yarn install --immutable

      - name: Lint
        run: 'yarn run format:check'

      - name: Audit
        run: yarn audit --groups=dependencies --level=high

      - name: Build dist
        run: yarn run build

      - name: Check build
        run: |
          if [[ $(git diff dist/) ]]; then
            echo "found changes not committed in final build"
            exit 1
          fi
